# Generated by Django 5.0.1 on 2024-02-13 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingregient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingregient',
            new_name='Ingredient',
        ),
    ]
